student_name = input("Enter name here:")
roll_number = int (input("Enter roll number here:"))
cgpa = float(input("Enter cgpa here:"))
print("Your name is", student_name)
print("Your roll number is", roll_number + 1)
print("Your cgpa is", cgpa*10,"\b%")
